# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./mainwindow.h 


#Source files
SOURCES += ./main.cpp \
    ./mainwindow.cpp 


#Resource file(s)
RESOURCES += dockwidgets.qrc
